/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SingulationDlg.java
 *
 * Created on May 3, 2011, 9:01:36 AM
 */

import com.mot.rfid.api3.Antennas.SingulationControl;
import com.mot.rfid.api3.INVENTORY_STATE;
import com.mot.rfid.api3.InvalidUsageException;
import com.mot.rfid.api3.OperationFailureException;
import com.mot.rfid.api3.SESSION;
import com.mot.rfid.api3.SL_FLAG;
import java.awt.event.ItemEvent;

/**
 *
 * @author CFRN78
` */
public class SingulationDlg extends javax.swing.JDialog {

    /** Creates new form SingulationDlg */
    public SingulationDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        if (RFIDMainDlg.rfidBase.getMyReader().ReaderCapabilities.isTagInventoryStateAwareSingulationSupported() == true)
            jCheckBoxStateAwareSingulation.setEnabled(true);
        else
            jCheckBoxStateAwareSingulation.setEnabled(false);
 
         short[] antennaList = RFIDMainDlg.rfidBase.getMyReader().Config.Antennas.getAvailableAntennas();
         // Add antennas
         for (int index = 0; index < antennaList.length; index++)
            jComboBoxAntennaID.addItem(String.valueOf(antennaList[index]));

         
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxStateAwareSingulation = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxInventoryState = new javax.swing.JComboBox();
        jComboBoxSLFlag = new javax.swing.JComboBox();
        jComboBoxAntennaID = new javax.swing.JComboBox();
        jComboBoxSession = new javax.swing.JComboBox();
        jButtonApply = new javax.swing.JButton();
        jTextFieldTagPopulation = new javax.swing.JTextField();
        jTextFieldTransitTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Singulation");
        setResizable(false);

        jLabel1.setText("Antenna");

        jLabel2.setText("Session");

        jLabel3.setText("Tag Population");

        jLabel4.setText("Tag Transit time");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jCheckBoxStateAwareSingulation.setText("State Aware Singulation");
        jCheckBoxStateAwareSingulation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                jCheckBoxStateAwareSingulationItemStateChanged(evt);
            }
        });

        jLabel5.setText("Inventory State");

        jLabel6.setText("SL Flag");

        jComboBoxInventoryState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "AB_FLIP" }));

        jComboBoxSLFlag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ASSERTED", "DEASSERTED", "SL_ALL" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxStateAwareSingulation)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSLFlag, 0, 99, Short.MAX_VALUE)
                            .addComponent(jComboBoxInventoryState, 0, 99, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxStateAwareSingulation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxInventoryState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxSLFlag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jComboBoxAntennaID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                jComboBoxAntennaIDItemStateChanged(evt);
            }
        });

        jComboBoxSession.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S0", "S1", "S2", "S3" }));

        jButtonApply.setText("Apply");
        jButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonApply, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTransitTime)
                            .addComponent(jComboBoxSession, 0, 89, Short.MAX_VALUE)
                            .addComponent(jComboBoxAntennaID, 0, 89, Short.MAX_VALUE)
                            .addComponent(jTextFieldTagPopulation))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxAntennaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTagPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTransitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonApply)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyActionPerformed
        int antennaID = jComboBoxAntennaID.getSelectedIndex();
        antennaID++;
        try {
            SingulationControl singulationControl = RFIDMainDlg.rfidBase.getMyReader().Config.Antennas.getSingulationControl(antennaID);
            SESSION session = singulationControl.getSession();
            switch (jComboBoxSession.getSelectedIndex())
            {
                case 0:
                    session = SESSION.SESSION_S0;
                    break;
                case 1:
                    session = SESSION.SESSION_S1;
                    break;
                case 2:
                    session = SESSION.SESSION_S2;
                    break;
                case 3:
                    session = SESSION.SESSION_S3;
                    break;
            }
            singulationControl.setSession(session);
            singulationControl.setTagPopulation(Short.parseShort(jTextFieldTagPopulation.getText()));
            singulationControl.setTagTransitTime(Short.parseShort(jTextFieldTransitTime.getText()));

 
            
            // Get State Aware Singulation State
            if (jCheckBoxStateAwareSingulation.isSelected())
            {
                singulationControl.Action.setPerformStateAwareSingulationAction(true);

                INVENTORY_STATE inventoryState = singulationControl.Action.getInventoryState();

                // Get Inventory State
                switch (jComboBoxInventoryState.getSelectedIndex())
                {
                    case 0:
                        inventoryState = INVENTORY_STATE.INVENTORY_STATE_A;
                        break;
                    case 1:
                        inventoryState = INVENTORY_STATE.INVENTORY_STATE_B;
                        break;
                    case 2:
                        inventoryState = INVENTORY_STATE.INVENTORY_STATE_AB_FLIP;                        
                        break;
                }
                singulationControl.Action.setInventoryState(inventoryState);

                SL_FLAG slFlag = singulationControl.Action.getSLFlag();

                // Get Inventory State
                switch (jComboBoxSLFlag.getSelectedIndex())
                {
                    case 0:
                        slFlag = SL_FLAG.SL_FLAG_ASSERTED;
                        break;
                    case 1:
                        slFlag = SL_FLAG.SL_FLAG_DEASSERTED;
                        break;
                    case 2:
                        slFlag = SL_FLAG.SL_ALL;
                        break;                        
                }
                singulationControl.Action.setSLFlag(slFlag);

            }
            else
                singulationControl.Action.setPerformStateAwareSingulationAction(false);
            
            // Set singulation control
            RFIDMainDlg.rfidBase.getMyReader().Config.Antennas.setSingulationControl(antennaID, singulationControl);
            RFIDMainDlg.rfidBase.postStatusNotification(RFIDBase.API_SUCCESS, null);

        } catch (InvalidUsageException ex) {
            RFIDMainDlg.rfidBase.postStatusNotification(RFIDBase.PARAM_ERROR, ex.getVendorMessage());
        } catch (OperationFailureException ex) {
            RFIDMainDlg.rfidBase.postStatusNotification(ex.getStatusDescription(), ex.getVendorMessage());
        }
    }//GEN-LAST:event_jButtonApplyActionPerformed

    private void jComboBoxAntennaIDItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_jComboBoxAntennaIDItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            int antennaID = jComboBoxAntennaID.getSelectedIndex();
            antennaID++;
            try {
                SingulationControl singulationControl = RFIDMainDlg.rfidBase.getMyReader().Config.Antennas.getSingulationControl(antennaID);

                jComboBoxSession.setSelectedIndex(singulationControl.getSession().getValue());
                jTextFieldTagPopulation.setText(String.valueOf(singulationControl.getTagPopulation()));
                jTextFieldTransitTime.setText(String.valueOf(singulationControl.getTagTransitTime()));

                // Get State Aware Singulation State
                if (singulationControl.Action.isPerformStateAwareSingulationActionSet())
                {
                    jCheckBoxStateAwareSingulation.setSelected(true);
                    jComboBoxInventoryState.setSelectedIndex(singulationControl.Action.getInventoryState().getValue());
                    jComboBoxSLFlag.setSelectedIndex(singulationControl.Action.getSLFlag().getValue());
                    jComboBoxInventoryState.setEnabled(true);
                    jComboBoxSLFlag.setEnabled(true);
                }
                else
                {
                    jCheckBoxStateAwareSingulation.setSelected(false);
                    jComboBoxInventoryState.setEnabled(false);
                    jComboBoxSLFlag.setEnabled(false);
                }

            } catch (InvalidUsageException ex) {
                RFIDMainDlg.rfidBase.postStatusNotification(RFIDBase.PARAM_ERROR, ex.getVendorMessage());
            } catch (OperationFailureException ex) {
                RFIDMainDlg.rfidBase.postStatusNotification(ex.getStatusDescription(), ex.getVendorMessage());
            }
        }
    }//GEN-LAST:event_jComboBoxAntennaIDItemStateChanged

    private void jCheckBoxStateAwareSingulationItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_jCheckBoxStateAwareSingulationItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED)
        {
            jComboBoxInventoryState.setEnabled(true);
            jComboBoxSLFlag.setEnabled(true);
        }
        else
        {
            jComboBoxInventoryState.setEnabled(false);
            jComboBoxSLFlag.setEnabled(false);
        }

    }//GEN-LAST:event_jCheckBoxStateAwareSingulationItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SingulationDlg dialog = new SingulationDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApply;
    private javax.swing.JCheckBox jCheckBoxStateAwareSingulation;
    private javax.swing.JComboBox jComboBoxAntennaID;
    private javax.swing.JComboBox jComboBoxInventoryState;
    private javax.swing.JComboBox jComboBoxSLFlag;
    private javax.swing.JComboBox jComboBoxSession;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldTagPopulation;
    private javax.swing.JTextField jTextFieldTransitTime;
    // End of variables declaration//GEN-END:variables

}
