/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SoftwareUpdateDlg.java
 *
 * Created on Jun 2, 2011, 10:44:45 PM
 */

import com.mot.rfid.api3.*;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.text.html.*;

/**
 *
 * @author CFRN78
 */
public class SoftwareUpdateDlg extends JDialog {

    SoftwareUpdateInfo softwareUpdateInfo;
    final static int interval = 1000;
    int progressBarValue;
    Timer timer;

    /** Creates new form SoftwareUpdateDlg */
    public SoftwareUpdateDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //Create a timer.
        timer = new Timer(interval, new ActionListener() {

            public void actionPerformed(ActionEvent evt) {
                if (progressBarValue == 100) {
                    //Toolkit.getDefaultToolkit().beep();
                    timer.stop();
                    jButtonStartUpdate.setEnabled(true);
                    jProgressBar1.setValue(0);
                    String str = "<html>" + "<font color=\"#FF0000\">" + "<b>" + "Software update completed." + "</b>" + "</font>" + "</html>";
                    jLabelStatus.setText(str);
                    return;
                }
                
                try {

                    UpdateStatus updateStatus = RFIDMainDlg.rfidBase.rm.getSoftwareUpdate().getUpdateStatus();
                    progressBarValue = updateStatus.getPercentage();
                    jProgressBar1.setValue(progressBarValue);
                    String str = "<html>" + "<font color=\"#008000\">" + "<b>" + updateStatus.getUpdateInfo().toString() + "</b>" + "</font>" + "</html>";
                    jLabelStatus.setText(str);

                } catch (InvalidUsageException ex) {
                    //ex.printStackTrace();
                } catch (OperationFailureException ex) {
                    //ex.printStackTrace();
                    String str = "<html>" + "<font color=\"#008000\">" + "<b>" + "Software update is in process......." + "</b>" + "</font>" + "</html>";
                    jLabelStatus.setText(str);
                    if(ex.getResults() == RFIDResults.RFID_RM_NO_UPDATION_IN_PROGRESS)
                    {
                        //Toolkit.getDefaultToolkit().beep();
                        timer.stop();
                        jButtonStartUpdate.setEnabled(true);
                        jProgressBar1.setValue(0);
                        str = "<html>" + "<font color=\"#FF0000\">" + "<b>" + ex.getStatusDescription() + "</b>" + "</font>" + "</html>";
                        jLabelStatus.setText(str);
                        return;
                    }

                }

            }
        });

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new JLabel();
        jTextFieldLocation = new JTextField();
        jButtonStartUpdate = new JButton();
        jLabelStatus = new JLabel();
        jProgressBar1 = new JProgressBar();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jTextFieldUserName = new JTextField();
        jLabel2 = new JLabel();
        jPasswordField = new JPasswordField();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Software Update");
        setResizable(false);

        jLabel3.setText("Location");

        jButtonStartUpdate.setText("Start Update");
        jButtonStartUpdate.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonStartUpdateActionPerformed(evt);
            }
        });

        jProgressBar1.setStringPainted(true);

        jPanel1.setBorder(BorderFactory.createTitledBorder("FTP Info"));

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        jPasswordField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField, GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextFieldUserName, GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUserName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLocation, GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonStartUpdate, GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jLabelStatus, GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLocation, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStartUpdate)
                .addGap(18, 18, 18)
                .addComponent(jLabelStatus, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButtonStartUpdateActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonStartUpdateActionPerformed

        softwareUpdateInfo = new SoftwareUpdateInfo();
        softwareUpdateInfo.setHostName(jTextFieldLocation.getText());
        softwareUpdateInfo.setUserName(jTextFieldUserName.getText());
        softwareUpdateInfo.setPassword(jPasswordField.getText());
        try {
            RFIDMainDlg.rfidBase.rm.getSoftwareUpdate().Update(softwareUpdateInfo);

            jButtonStartUpdate.setEnabled(false);
            progressBarValue = 0;
            String str = "<html>" + "<font color=\"#008000\">" + "<b>" + "Software update is in process......." + "</b>" + "</font>" + "</html>";
            jLabelStatus.setText(str);
            timer.start();

            RFIDMainDlg.rfidBase.postStatusNotification(RFIDBase.API_SUCCESS, null);

            } catch (InvalidUsageException ex) {
                RFIDMainDlg.rfidBase.postStatusNotification(RFIDBase.PARAM_ERROR, ex.getVendorMessage());
            } catch (OperationFailureException ex) {
                RFIDMainDlg.rfidBase.postStatusNotification(ex.getStatusDescription(), ex.getVendorMessage());
            }

    }//GEN-LAST:event_jButtonStartUpdateActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SoftwareUpdateDlg dialog = new SoftwareUpdateDlg(new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonStartUpdate;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabelStatus;
    private JPanel jPanel1;
    private JPasswordField jPasswordField;
    private JProgressBar jProgressBar1;
    private JTextField jTextFieldLocation;
    private JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables

}
